### ISSUE TITLE
Add defibrillators with valid `opening_hours`

### ISSUE THREAD

**Issue by habi** [OpenBracketsCH/defikarte.ch-app#162]
Version 1 of [this Defibrillator](https://www.openstreetmap.org/node/10751066307/history) was added with free-text opening hours.
I think it would be cool if the `opening_hours` tag is added correctly/[valid](https://projets.pavie.info/yohours/?oh=Su-Fr%2008:30-17:00;%20Sa%2012:00-17:00).

Maybe the Defikarte-App could introduce an opening hours setter, like [Vespucci](http://vespucci.io/help/en/Opening%20hours/), [Every Door](https://every-door.app/) or [StreetComplete](https://streetcomplete.app/).

**Comment by elektrolytmangel** [comment]
We have an opening_hours validation, I will check on that and why it was accepted. I think the library we use, allows multiple languages and  is probably not that strict. 
The idea for an editor is great, we check that, thanks for the support!

**Comment by chnuessli** [comment]
Hi @elektrolytmangel as discussed on the CH Mailing list, the issue still activ. Have you got a solution? The App User is at the moment the leader in the Project of the Month from Swiss OSM and the eyes are on us :)

**Comment by elektrolytmangel** [comment]
Thanks for the reminder. I fixed the issue. Now the value from the 1st version of the defibrillator is not accepted any more. We also show a message which helps the user to fix the errors/warnings.
Deployment on android and ios is waiting. Web see: [PR](https://github.com/elektrolytmangel/defikarte-form/pull/16)

**Comment by elektrolytmangel** [comment]
Apps are published to Google Play Store and Apple App Store.
