### ISSUE TITLE
Trailing space in `defibrillator:location` value

### ISSUE THREAD

**Issue by habi** [OpenBracketsCH/defikarte.ch-app#163]
Version 1 of [this Defibrillator](https://www.openstreetmap.org/node/10751066307/history) was added `defibrillator:location=Haus GZ ` (note the trailing space).

The Defikarte-App should strip any trailing spaces in the location description (more precisely, in all values) on upload.

**Comment by habi** [comment]
Noticed when taking care of https://www.openstreetmap.org/note/3614889

**Comment by chnuessli** [comment]
@elektrolytmangel Is there any solution on your side, to this? Same for https://github.com/elektrolytmangel/defikarte-form

**Comment by elektrolytmangel** [comment]
No, this is not fixed so far.

**Comment by chnuessli** [comment]
@habi Were there any discussions on OSM-Side to automatically remove whitespaces when uploading new data? I think this is not only a problem on our side, but on every users side?

**Comment by habi** [comment]
I cannot force ID to submit a changeset with any trailing spaces in any `key=value` pair, trailing spaces are *always* stripped it seems.
In JOSM, any trailing spaces are trimmed automatically when manually entering a `value`, see attached screencast.

So I guess it's the responsibility of any editor to strip *trailing* spaces... And not implemented in the OSM API itself.

https://github.com/user-attachments/assets/fc73e87b-8ac2-4a86-a7c0-8db4da389624

**Comment by habi** [comment]
Here's a search to find nodes with a description with a trailing space: https://osm.li/Pq_
