### ISSUE TITLE
Upgrade Expo to SDK50

### ISSUE THREAD

**Issue by elektrolytmangel** [OpenBracketsCH/defikarte.ch-app#176]
Approximately in January the new expo SDK50 will be release. Upgrade to the newest version and test issues.

**Comment by elektrolytmangel** [comment]
Updated to ExpoSDK 50. Ready to test.

**Comment by chnuessli** [comment]
Did you push the branch or where can one test it?

**Comment by elektrolytmangel** [comment]
I will test localy and then push a new version to main to deploy to test-tracks (Testflight and Google Play) until the end of the week.

**Comment by elektrolytmangel** [comment]
Local tests successful. Run production builds and deploy to test-tracks.

**Comment by elektrolytmangel** [comment]
iOS and Android in Production.
