### ISSUE TITLE
Form for access values not intuitive

### ISSUE THREAD

**Issue by eginhard** [OpenBracketsCH/defikarte.ch-app#179]
Somebody on the OSM World Discord server noticed that a lot of defibrillators in Switzerland are tagged with `access=no` (>90% of the worldwide cases: https://overpass-turbo.eu/s/1Jda). Most of them come from the Defikarte and one related import (https://www.openstreetmap.org/changeset/134128958). Many indeed seem to be located in companies/offices, but `access=private` would be a better fit there. Others are quite clearly meant for public access (https://www.openstreetmap.org/node/11536529969, https://www.openstreetmap.org/node/10781820605), or are even explicitly tagged that way in the `description` (https://www.openstreetmap.org/node/11371093369, https://www.openstreetmap.org/node/10203684217, https://www.openstreetmap.org/node/7786275859).

I guess this is because the Defikarte app and website form's switch for "Zugänglich/Accessible" defaults to `False`. There is no explanation at all for what this term means, so many people might just leave the default value. Providing an explicit choice between public and private access might be better here, defaulting to public (and otherwise tagging `access=private` instead of `access=no`).

**Comment by elektrolytmangel** [comment]
Thank you for opening the issue! I will discuss this with @chnuessli and create a fix for the issue.

**Comment by chnuessli** [comment]
Hi @eginhard. Thank you for reporting this isse.

For me there are two issues identified in this issue.
1. The problem with the selection on the defi-form. Maybe there should be a dropdown with available options regarding wo the osm wiki.
2. The problem with the imported data. I will check on that and find a solution that suits the community.

For me, access=no is and was always for defis that are not accessible fast and free. But permissive or private are more adequate sometimes.

**Comment by eginhard** [comment]
@chnuessli Yes, that sounds good.

**Comment by eginhard** [comment]
Sorry for the late feedback @elektrolytmangel Yes, that looks good, thanks for updating it!

**Comment by elektrolytmangel** [comment]
Thanks! An update for the app with similar functionality is on the way. I will update the issue as soon it is live on iOS and Android.

**Comment by elektrolytmangel** [comment]
The feature is live on iOS and will be the net hours / days n Anroid.
