### ISSUE TITLE
Add Defikarte to Taginfo Projects

### ISSUE THREAD

**Issue by danieldegroot2** [OpenBracketsCH/defikarte.ch-app#180]
Show the OpenStreetMap community what [data](https://wiki.openstreetmap.org/wiki/Tags) you are using. Add Defikarte to the [list](https://taginfo.openstreetmap.org/projects) of [Taginfo Projects](https://github.com/taginfo/taginfo-projects).

_Sidenote: This project is using uMap. Usually uMap projects are not included in Taginfo. It may be okay since it is maintained, external website and app._

**Comment by chnuessli** [comment]
Hi @danieldegroot2. I will check on this, and inform you on this Issue.

**Comment by chnuessli** [comment]
There's a pull-request for the taginfo-project: https://github.com/taginfo/taginfo-projects/pull/199
taginfo.json is added in this commit: https://github.com/OpenBracketsCH/defikarte.ch/commit/f448270a97308a6908a8bc8a02bd51767ff7d416

But, i added it to the defikarte_repo not app.

**Comment by chnuessli** [comment]
Hi @danieldegroot2 
Yes wou were right. This file was missing and was not merged since the relaunch of the website.
I've created it again and you can find it here: https://github.com/OpenBracketsCH/defikarte.ch/blob/main/taginfo.json
Or https://defikarte.ch/taginfo.json
