### ISSUE TITLE
Add Defikarte to Defibrillator wiki page

### ISSUE THREAD

**Issue by danieldegroot2** [OpenBracketsCH/defikarte.ch-app#181]
Suggestion: Add Defikarte to [Defibrillator wiki page](https://wiki.openstreetmap.org/wiki/Tag%3Aemergency%3Ddefibrillator)

**Comment by chnuessli** [comment]
Will do it asap.

**Comment by chnuessli** [comment]
Done
https://wiki.openstreetmap.org/wiki/Tag:emergency%3Ddefibrillator#Maps_and_applications_showing_AED
