### ISSUE TITLE
Add GitHub repository link

### ISSUE THREAD

**Issue by danieldegroot2** [OpenBracketsCH/defikarte.ch-app#182]
Not sure how it is for the app, but the website does not seem to have a link to the GitHub repository (to report issues, not AEDs ofc).

**Comment by elektrolytmangel** [comment]
Good point. It is missing in the app and the website. We will add the link in both.

**Comment by chnuessli** [comment]
Thank you @danieldegroot2 i will insert that asap on the website. @elektrolytmangel will do it for the next version of the app.

**Comment by chnuessli** [comment]
Done on the website: https://defikarte.ch/about.html
