### ISSUE TITLE
Add repository embed image

### ISSUE THREAD

**Issue by danieldegroot2** [OpenBracketsCH/defikarte.ch-app#183]
You should be able to add a logo / embed image for the GitHub repository. See
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/customizing-your-repositorys-social-media-preview

(Or similar to [website repository](https://github.com/OpenBracketsCH/defikarte.ch)); (Rich) embed in Discord:

![image](https://github.com/OpenBracketsCH/defikarte.ch-app/assets/67521919/4559d1f5-6dba-4fee-8829-1f7e9f41264c)

**Comment by chnuessli** [comment]
Good point. Will do it asap

**Comment by chnuessli** [comment]
Done.
