### ISSUE TITLE
access=no Option entfernen

### ISSUE THREAD

**Issue by chnuessli** [OpenBracketsCH/defikarte.ch-app#190]
Aufgrund von Rückmeldungen aus der OSM Community ist der access-Tag nicht mehr mit der Option ="no" zu versehen und diese Option zu streichen. D.H Defis die keinen Zugang ermöglichen sollen anders getaggt werden. Bitte Option asap streichen.

**Comment by elektrolytmangel** [comment]
Wurde in der app und im backend entfernt. Ältere Versionen der App haben zwar noch die Option "no", der Wert wird aber nicht mehr nach OSM übertragen.
