### ISSUE TITLE
`level`-Werte für Stockwerke

### ISSUE THREAD

**Issue by habi** [OpenBracketsCH/defikarte.ch-app#194]
Die Defikarte-App scheint den `level`-Wert als Freitext einzugeben, jedenfalls irgeneine Version davon, siehe https://github.com/OpenBracketsCH/defikarte.ch-app/issues/151

In den OpenStreetMap-Daten finden sich viele solche Werte, die dann nicht (einfach) maschinenlesbar sind, siehe Screenshot aus taginfo.openstreetmap.ch. *Alle* diese Daten stammen aus der defikarte-App.
![Screenshot aus taginfo.openstreetmap.ch](https://github.com/user-attachments/assets/53aa2972-a406-4f22-b96d-cc7a87294796)

Laut [OSM Wiki](https://wiki.openstreetmap.org/wiki/DE:Key:level) sollte `level` mit ganzen Zahlen erfasst werden, allfälliger Freitext gehört in `level:ref`.

Ist es möglich, das anzupassen, dass so keine 'falschen' Daten in der OpenStreetMap-Datenbank landen, die dann immer wieder händisch korrigiert werden müssen?

**Comment by elektrolytmangel** [comment]
Danke für die Meldung. Ich passe das an.

**Comment by chnuessli** [comment]
App now accepts only digits as input field in the level segment. also negative digits are possible. Android and iOS Apps are updated and available in the store.
