### ISSUE TITLE
defikarte app does not wait for GNSS fix, resulting in wrong position

### ISSUE THREAD

**Issue by Rainer-o** [OpenBracketsCH/defikarte.ch-app#200]
Some defi nodes that are added with the defikarte.ch app are far from the real position. It looks like the app does not wait for a GNSS fix, but takes the last position that is stored in the smartphone.
An example: https://www.openstreetmap.org/node/9407839033 is somewhere in the forest between Mainz and Trier in Germany, but the location typed in by the user is "Ittigen", nearby Bern in Switzerland. Unfortunately to unprecise to shift the node; I haven't yet deleted it as an example. Another is https://www.openstreetmap.org/node/10240188690.

In the past the Wheelmap App had the same issue.

**Comment by chnuessli** [comment]
@elektrolytmangel wasn't there a bug that can trigger this issue? I think we fixed that, didn't we?

**Comment by Rainer-o** [comment]
Yeah, those nodes that are far away are 2 - 3 years old.
Seems the defikarte_app changesets do not have the app version in the CS meta data. 
So if the issue is solved already, I will delete the "far away nodes", since the real position is unclear.

**Comment by chnuessli** [comment]
I think they can be deleted.
