### ISSUE TITLE
ios copy paste marker in system language

### ISSUE THREAD

**Issue by chnuessli** [OpenBracketsCH/defikarte.ch-app#40]
die copy paste funktion sollte in der systemsprache angezeigt werden

**Comment by chnuessli** [comment]
https://stackoverflow.com/questions/11224969/localizing-the-cutcopypaste-menu-on-ios

**Comment by elektrolytmangel** [comment]
this does not work. I cannot change this dialogs that easy. I will say, this has low priority eighter.
