### ISSUE TITLE
Use other map provider (OSM native)

### ISSUE THREAD

**Issue by elektrolytmangel** [OpenBracketsCH/defikarte.ch-app#59]
Instead of using the native map modules and view, use OSM tiles to provide better base data. For this, we have probably to change to the MapboxSDK or some other solutions. With the current map-framework we can only overlay OSM-Tiles, which lead to bad performance (we have already some issues with performance because of the custom markers)

**Comment by elektrolytmangel** [comment]
I added a tile overlay with osm data. On iOS it works fine, android does still have some performance issues / flickering of the markers

**Comment by elektrolytmangel** [comment]
#74 duplicated

**Comment by elektrolytmangel** [comment]
Do not only use a tile overlay, use directly osm data, on iOS and Android (with the overlay, on android there is some issue with the picture-resolution)

**Comment by chnuessli** [comment]
in combination with #107

**Comment by elektrolytmangel** [comment]
Does not look like an issue anymore.
