### ISSUE TITLE
i18n - translation

### ISSUE THREAD

**Issue by elektrolytmangel** [OpenBracketsCH/defikarte.ch-app#60]
Add translation to french, italian and english?

**Comment by elektrolytmangel** [comment]
translate also the data incoming from OSM?

**Comment by chnuessli** [comment]
transifex is too expensive. maybe we have to translate everything manually.
do you have a good idea for the osm data?
the whole app to translate is imho very low prio.

**Comment by elektrolytmangel** [comment]
We can probably use: https://libretranslate.com/ is open source and free, and looks somehow simple to handle, and for the OSM data this should be enough. But it does not recognize the language. But I think for the most basic translations, this could work.

**Comment by elektrolytmangel** [comment]
Feature is added to iOS and Android.
