### ISSUE TITLE
Code Refactoring

### ISSUE THREAD

**Issue by chnuessli** [OpenBracketsCH/defikarte.ch-app#71]
# Code Refactoring

## Written code

As it is our first app, the code is written day by day and just straight forward. Maybe we should consider a code refactoring. The code is written in JS, C#, HTML and CSS and uses React Native. 

## Best outcome

Someone willing and able to refactor our code with an external view and expertise can refactor our code and we can learn as much as we can and have a clean code base for future enhancements.

**Best thanks**

**Comment by elektrolytmangel** [comment]
@Raknison123 are you interested in helping in the .net or js part?

**Comment by elektrolytmangel** [comment]
Code refactoring is low priority, and also atm not needed anymore. Close the issue now.
